export { default as HitsResolver } from './HitsResolver'
export { default as SearchkitResolver } from './ResultsResolver'
export { default as FacetsResolver } from './FacetsResolver'
export { default as SummaryResolver } from './SummaryResolver'
export { default as FacetResolver } from './FacetResolver'
